import type { Metadata } from 'next'

import { Pretendard } from '@wontory/ui/pretendard'
import { ThemeProvider } from '@wontory/ui/theme-provider'
import '@wontory/ui/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className={Pretendard.variable} suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
